### ISSUE TITLE
 Added 0 3' UTRs

### ISSUE THREAD

**Issue by gushiro** [danilotat/UTR_add_extend_GTF#2]
Hi,
Thank you for developing your tool. I tried to run your script but no UTRs are extended. The output is:

```
Processing chromosome Scaffold5
Added 0 3' UTRs
```

For so for all the scaffolds

Any suggestion?

Thank you

**Comment by danilotat** [comment]
Hi @gushiro , give me more details to understand the scenario. 

Which GTF are you using? Is it from Ensembl? Attach also the command you're using and some lines of the log (even a single scaffold is enough).

Note that the processing of adding 3'UTR is different from extending. As I stated in the README, a 3'UTR is only added in the rare case where a protein coding gene has no 3'UTR record.  So it's okay to see no _novel_ UTR when doing extension.
